# Common compilation definitions.
COMPILER := g++
LINKER := ar
SYMBOLIC_LINK := ln
COMMON_COMPILE_FLAGS := -Wall -Werror -std=c++11
LIBRARY_COMPILE_FLAGS := -fPIC -c
LIBRARY_BUILD_FLAGS := -shared
ENGINE_ROOT=$(shell pwd)/

# Add debug flags to compilation.
DEBUG_COMPILE_FLAGS := -g
#COMMON_COMPILE_FLAGS += $(DEBUG_COMPILE_FLAGS)

# Common module definitions.
LIBRARY_OUTPUT_PATH := $(ENGINE_ROOT)lib/
EXECUTABLE_OUTPUT_PATH := $(ENGINE_ROOT)bin/
INCLUDE_SUBDIRECTORY := include/
SOURCE_SUBDIRECTORY := source/
BUILD_SUBDIRECTORY := build/

# Engine common library definitions.
ENGINE_COMMON_NAME := engine_common
ENGINE_COMMON_ROOT := $(ENGINE_ROOT)$(ENGINE_COMMON_NAME)/
ENGINE_COMMON_VERSION_MAJOR := 1
ENGINE_COMMON_VERSION_MINOR := 0
ENGINE_COMMON_VERSION_BUILD := 0
ENGINE_COMMON_INCLUDE_FLAGS := -I$(ENGINE_COMMON_ROOT)$(INCLUDE_SUBDIRECTORY)
ENGINE_COMMON_LIBRARY_FLAGS := -lm
ENGINE_COMMON_SOURCE_PATH := $(ENGINE_COMMON_ROOT)$(SOURCE_SUBDIRECTORY)
ENGINE_COMMON_BUILD_PATH := $(ENGINE_COMMON_ROOT)$(BUILD_SUBDIRECTORY)
ENGINE_COMMON_COMPILE_FLAGS := $(ENGINE_COMMON_INCLUDE_FLAGS) $(COMMON_COMPILE_FLAGS) $(LIBRARY_COMPILE_FLAGS)
ENGINE_COMMON_BUILD_FLAGS := $(ENGINE_COMMON_LIBRARY_FLAGS)
ENGINE_COMMON_OBJECTS := \
	$(ENGINE_COMMON_BUILD_PATH)renderer/attribute.o \
	$(ENGINE_COMMON_BUILD_PATH)renderer/buffer_layout.o \
	$(ENGINE_COMMON_BUILD_PATH)allocatable.o \
	$(ENGINE_COMMON_BUILD_PATH)error_stack.o \
	$(ENGINE_COMMON_BUILD_PATH)file.o \
	$(ENGINE_COMMON_BUILD_PATH)math_common.o \
	$(ENGINE_COMMON_BUILD_PATH)matrix3x3.o \
	$(ENGINE_COMMON_BUILD_PATH)matrix4x4.o \
	$(ENGINE_COMMON_BUILD_PATH)memory_manager.o \
	$(ENGINE_COMMON_BUILD_PATH)vector2.o \
	$(ENGINE_COMMON_BUILD_PATH)vector3.o \
	$(ENGINE_COMMON_BUILD_PATH)vector4.o

# Main engine module definitions.
ENGINE_NAME := engine
ENGINE_VERSION_MAJOR := 1
ENGINE_VERSION_MINOR := 0
ENGINE_VERSION_BUILD := 0
ENGINE_INCLUDE_PATH := $(ENGINE_ROOT)$(INCLUDE_SUBDIRECTORY)
ENGINE_SOURCE_PATH := $(ENGINE_ROOT)$(SOURCE_SUBDIRECTORY)
ENGINE_BUILD_PATH := $(ENGINE_ROOT)$(BUILD_SUBDIRECTORY)
ENGINE_INCLUDE_FLAGS := \
    -I$(ENGINE_INCLUDE_PATH) \
    -I/usr/include/SDL2/ \
    $(ENGINE_COMMON_INCLUDE_FLAGS)
ENGINE_LIBRARY_FLAGS := \
    -L$(LIBRARY_OUTPUT_PATH) \
	-lSDL2 \
	-lSDL2main
ENGINE_COMPILE_FLAGS := $(ENGINE_INCLUDE_FLAGS) $(COMMON_COMPILE_FLAGS) $(LIBRARY_COMPILE_FLAGS)
ENGINE_BUILD_FLAGS := $(ENGINE_LIBRARY_FLAGS)
ENGINE_OBJECTS := \
    $(ENGINE_BUILD_PATH)engine.o \
    $(ENGINE_BUILD_PATH)engine_export.o \
    $(ENGINE_BUILD_PATH)sdl_window.o \
    $(ENGINE_BUILD_PATH)window.o

# Game manager module definitions.
GAME_MANAGER_NAME := game_manager
GAME_MANAGER_ROOT := $(ENGINE_ROOT)$(GAME_MANAGER_NAME)/
GAME_MANAGER_VERSION_MAJOR := 1
GAME_MANAGER_VERSION_MINOR := 0
GAME_MANAGER_VERSION_BUILD := 0
GAME_MANAGER_INCLUDE_PATH := $(GAME_MANAGER_ROOT)$(INCLUDE_SUBDIRECTORY)
GAME_MANAGER_SOURCE_PATH := $(GAME_MANAGER_ROOT)$(SOURCE_SUBDIRECTORY)
GAME_MANAGER_BUILD_PATH := $(GAME_MANAGER_ROOT)$(BUILD_SUBDIRECTORY)
GAME_MANAGER_INCLUDE_FLAGS := \
	$(ENGINE_COMMON_INCLUDE_FLAGS) \
	-I$(ENGINE_INCLUDE_PATH) \
	-I$(GAME_MANAGER_INCLUDE_PATH)
GAME_MANAGER_LIBRARY_FLAGS := \
	-L$(LIBRARY_OUTPUT_PATH)
GAME_MANAGER_COMPILE_FLAGS := \
	$(GAME_MANAGER_INCLUDE_FLAGS) \
	$(GAME_MANAGER_LIBRARY_FLAGS) \
	$(COMMON_COMPILE_FLAGS) $(LIBRARY_COMPILE_FLAGS)
GAME_MANAGER_OBJECTS := \
	$(GAME_MANAGER_BUILD_PATH)game_manager.o \
	$(GAME_MANAGER_BUILD_PATH)game_manager_export.o \
	$(GAME_MANAGER_BUILD_PATH)game_module.o

# Quake 2 common library definitions.
QUAKE2_COMMON_NAME := quake2_common
QUAKE2_COMMON_ROOT := $(ENGINE_ROOT)$(QUAKE2_COMMON_NAME)/
QUAKE2_COMMON_VERSION_MAJOR := 1
QUAKE2_COMMON_VERSION_MINOR := 0
QUAKE2_COMMON_VERSION_BUILD := 0
QUAKE2_COMMON_INCLUDE_PATH := $(QUAKE2_COMMON_ROOT)$(INCLUDE_SUBDIRECTORY)
QUAKE2_COMMON_SOURCE_PATH := $(QUAKE2_COMMON_ROOT)$(SOURCE_SUBDIRECTORY)
QUAKE2_COMMON_BUILD_PATH := $(QUAKE2_COMMON_ROOT)$(BUILD_SUBDIRECTORY)
QUAKE2_COMMON_INCLUDE_FLAGS := \
	-I$(QUAKE2_COMMON_INCLUDE_PATH) \
	$(ENGINE_COMMON_INCLUDE_FLAGS)
QUAKE2_COMMON_LIBRARY_FLAGS := \
	-L$(LIBRARY_OUTPUT_PATH)
QUAKE2_COMMON_COMPILE_FLAGS := \
	$(QUAKE2_COMMON_INCLUDE_FLAGS) \
	$(QUAKE2_COMMON_LIBRARY_FLAGS) \
	$(COMMON_COMPILE_FLAGS) \
	$(LIBRARY_COMPILE_FLAGS)
QUAKE2_COMMON_OBJECTS := \
	$(QUAKE2_COMMON_BUILD_PATH)bsp_map.o \
	$(QUAKE2_COMMON_BUILD_PATH)bsp_painter.o \
	$(QUAKE2_COMMON_BUILD_PATH)bsp_parser.o \
	$(QUAKE2_COMMON_BUILD_PATH)pack_manager.o \
	$(QUAKE2_COMMON_BUILD_PATH)pcx_parser.o \
	$(QUAKE2_COMMON_BUILD_PATH)plane.o \
	$(QUAKE2_COMMON_BUILD_PATH)quake_file_manager.o \
	$(QUAKE2_COMMON_BUILD_PATH)wal_parser.o

# Client library definitions.
CLIENT_NAME := client
CLIENT_ROOT := $(ENGINE_ROOT)$(CLIENT_NAME)/
CLIENT_VERSION_MAJOR := 1
CLIENT_VERSION_MINOR := 0
CLIENT_VERSION_BUILD := 0
CLIENT_INCLUDE_PATH := $(CLIENT_ROOT)$(INCLUDE_SUBDIRECTORY)
CLIENT_SOURCE_PATH := $(CLIENT_ROOT)$(SOURCE_SUBDIRECTORY)
CLIENT_BUILD_PATH := $(CLIENT_ROOT)$(BUILD_SUBDIRECTORY)
CLIENT_INCLUDE_FLAGS := \
	$(ENGINE_COMMON_INCLUDE_FLAGS) \
	-I$(GAME_MANAGER_INCLUDE_PATH) \
	-I$(QUAKE2_COMMON_INCLUDE_PATH) \
	-I$(CLIENT_INCLUDE_PATH)
CLIENT_LIBRARY_FLAGS := \
	-L$(LIBRARY_OUTPUT_PATH) \
	-l$(QUAKE2_COMMON_NAME)
CLIENT_COMPILE_FLAGS := \
	$(CLIENT_INCLUDE_FLAGS) \
	$(COMMON_COMPILE_FLAGS) \
	$(LIBRARY_COMPILE_FLAGS)
CLIENT_BUILD_FLAGS := $(CLIENT_LIBRARY_FLAGS)
CLIENT_OBJECTS := \
	$(CLIENT_BUILD_PATH)camera.o \
	$(CLIENT_BUILD_PATH)client_export.o \
	$(CLIENT_BUILD_PATH)entity_model.o \
	$(CLIENT_BUILD_PATH)game_client.o \
	$(CLIENT_BUILD_PATH)md2_parser.o \
	$(CLIENT_BUILD_PATH)quake_normals.o

# OpenGL renderer library definitions.
OPENGL_NAME := opengl_renderer
OPENGL_ROOT = $(ENGINE_ROOT)$(OPENGL_NAME)/
OPENGL_VERSION_MAJOR := 1
OPENGL_VERSION_MINOR := 0
OPENGL_VERSION_BUILD := 0
OPENGL_INCLUDE_PATH := $(OPENGL_ROOT)$(INCLUDE_SUBDIRECTORY)
OPENGL_INCLUDE_FLAGS := \
	$(ENGINE_COMMON_INCLUDE_FLAGS) \
	-I$(OPENGL_INCLUDE_PATH)
OPENGL_SOURCE_PATH := $(OPENGL_ROOT)$(SOURCE_SUBDIRECTORY)
OPENGL_BUILD_PATH := $(OPENGL_ROOT)$(BUILD_SUBDIRECTORY)
OPENGL_LIBRARY_FLAGS := \
    -L$(LIBRARY_OUTPUT_PATH) \
    -lGL -lGLU -lGLEW -l$(ENGINE_COMMON_NAME)
OPENGL_COMPILE_FLAGS := $(OPENGL_INCLUDE_FLAGS) $(OPENGL_LIBRARY_FLAGS) $(COMMON_COMPILE_FLAGS) $(LIBRARY_COMPILE_FLAGS)
OPENGL_BUILD_FLAGS := $(OPENGL_LIBRARY_FLAGS)
OPENGL_OBJECTS := \
    $(OPENGL_BUILD_PATH)attribute.o \
    $(OPENGL_BUILD_PATH)buffer.o \
    $(OPENGL_BUILD_PATH)buffer_layout.o \
    $(OPENGL_BUILD_PATH)common.o \
    $(OPENGL_BUILD_PATH)index_buffer.o \
    $(OPENGL_BUILD_PATH)material.o \
    $(OPENGL_BUILD_PATH)material_layout.o \
    $(OPENGL_BUILD_PATH)opengl_export.o \
    $(OPENGL_BUILD_PATH)renderer.o \
    $(OPENGL_BUILD_PATH)resources.o \
    $(OPENGL_BUILD_PATH)texture.o \
    $(OPENGL_BUILD_PATH)variable.o

# List of libraries.
LIBRARIES := \
	$(ENGINE_COMMON_NAME) \
    $(ENGINE_NAME) \
	$(GAME_MANAGER_NAME) \
	$(QUAKE2_COMMON_NAME) \
	$(CLIENT_NAME) \
	$(OPENGL_NAME)

# Quake 2 executable parameters.
QUAKE2_NAME := quake2
QUAKE2_ROOT := $(ENGINE_ROOT)$(QUAKE2_NAME)/
QUAKE2_INCLUDE_PATH := $(QUAKE2_ROOT)$(INCLUDE_SUBDIRECTORY)
QUAKE2_SOURCE_PATH := $(QUAKE2_ROOT)$(SOURCE_SUBDIRECTORY)
QUAKE2_BUILD_PATH := $(QUAKE2_ROOT)$(BUILD_SUBDIRECTORY)
QUAKE2_INCLUDE_FLAGS := \
	$(ENGINE_COMMON_INCLUDE_FLAGS) \
	-I$(ENGINE_INCLUDE_PATH) \
	-I$(GAME_MANAGER_INCLUDE_PATH) \
	-I$(CLIENT_INCLUDE_PATH) \
	-I$(OPENGL_INCLUDE_PATH)
QUAKE2_LIBRARY_FLAGS := \
	-L$(LIBRARY_OUTPUT_PATH) \
	$(addprefix -l, $(LIBRARIES))
QUAKE2_COMPILE_FLAGS := \
	$(QUAKE2_INCLUDE_FLAGS) \
	$(COMMON_COMPILE_FLAGS) \
	-c
QUAKE2_OBJECTS := \
	$(QUAKE2_BUILD_PATH)main.o

# Quake II executable definitions.
QUAKE2_NAME=quake2

# Main make target.
all: $(QUAKE2_NAME)

# Library targets.
libraries: create_library_directory $(LIBRARIES)

# Game executable target.
$(QUAKE2_NAME): BUILD_PATH := $(QUAKE2_BUILD_PATH)
$(QUAKE2_NAME): libraries create_executable_directory create_$(QUAKE2_NAME)_build_directory $(QUAKE2_OBJECTS)
	$(COMPILER) -o $(EXECUTABLE_OUTPUT_PATH)$@ $(QUAKE2_OBJECTS) $(QUAKE2_LIBRARY_FLAGS)
$(QUAKE2_BUILD_PATH)%.o : $(QUAKE2_SOURCE_PATH)%.cpp
	$(COMPILER) -o $@ $< $(QUAKE2_COMPILE_FLAGS)

# Engine common library target.
# TODO: Can probably put these defs into a macro.
$(ENGINE_COMMON_NAME): BUILD_PATH := $(ENGINE_COMMON_BUILD_PATH) $(ENGINE_COMMON_BUILD_PATH)renderer/
$(ENGINE_COMMON_NAME): BUILD_OBJECTS := $(ENGINE_COMMON_OBJECTS)
$(ENGINE_COMMON_NAME): BUILD_FLAGS := $(ENGINE_COMMON_BUILD_FLAGS)
$(ENGINE_COMMON_NAME): VERSION_MAJOR := $(ENGINE_COMMON_VERSION_MAJOR)
$(ENGINE_COMMON_NAME): VERSION_FULL := $(VERSION_MAJOR).$(ENGINE_COMMON_VERSION_MINOR).$(ENGINE_COMMON_VERSION_BUILD)
$(ENGINE_COMMON_NAME): create_$(ENGINE_COMMON_NAME)_build_directory $(ENGINE_COMMON_OBJECTS)
$(ENGINE_COMMON_BUILD_PATH)%.o : $(ENGINE_COMMON_SOURCE_PATH)%.cpp
	$(COMPILER) -o $@ $< $(ENGINE_COMMON_COMPILE_FLAGS)

# Base engine library target.
$(ENGINE_NAME): BUILD_PATH := $(ENGINE_BUILD_PATH)
$(ENGINE_NAME): BUILD_OBJECTS := $(ENGINE_OBJECTS)
$(ENGINE_NAME): BUILD_FLAGS := $(ENGINE_BUILD_FLAGS)
$(ENGINE_NAME): VERSION_MAJOR := $(ENGINE_VERSION_MAJOR)
$(ENGINE_NAME): VERSION_FULL := $(VERSION_MAJOR).$(ENGINE_VERSION_MINOR).$(ENGINE_VERSION_BUILD)
$(ENGINE_NAME): create_$(ENGINE_NAME)_build_directory $(ENGINE_OBJECTS)
$(ENGINE_BUILD_PATH)%.o : $(ENGINE_SOURCE_PATH)%.cpp
	$(COMPILER) -o $@ $< $(ENGINE_COMPILE_FLAGS)

# Game manager library target.
$(GAME_MANAGER_NAME): BUILD_PATH := $(GAME_MANAGER_BUILD_PATH)
$(GAME_MANAGER_NAME): BUILD_OBJECTS := $(GAME_MANAGER_OBJECTS)
$(GAME_MANAGER_NAME): VERSION_MAJOR := $(GAME_MANAGER_VERSION_MAJOR)
$(GAME_MANAGER_NAME): VERSION_FULL := $(VERSION_MAJOR).$(GAME_MANAGER_VERSION_MINOR).$(GAME_MANAGER_VERSION_BUILD)
$(GAME_MANAGER_NAME): create_$(GAME_MANAGER_NAME)_build_directory $(GAME_MANAGER_OBJECTS)
$(GAME_MANAGER_BUILD_PATH)%.o : $(GAME_MANAGER_SOURCE_PATH)%.cpp
	$(COMPILER) -o $@ $< $(GAME_MANAGER_COMPILE_FLAGS)

# Quake 2 common library.
$(QUAKE2_COMMON_NAME): BUILD_PATH := $(QUAKE2_COMMON_BUILD_PATH)
$(QUAKE2_COMMON_NAME): BUILD_OBJECTS := $(QUAKE2_COMMON_OBJECTS)
$(QUAKE2_COMMON_NAME): VERSION_MAJOR := $(QUAKE2_COMMON_VERSION_MAJOR)
$(QUAKE2_COMMON_NAME): VERSION_FULL := $(VERSION_MAJOR).$(QUAKE2_COMMON_VERSION_MINOR).$(QUAKE2_COMMON_VERSION_BUILD)
$(QUAKE2_COMMON_NAME): create_$(QUAKE2_COMMON_NAME)_build_directory $(QUAKE2_COMMON_OBJECTS)
$(QUAKE2_COMMON_BUILD_PATH)%.o : $(QUAKE2_COMMON_SOURCE_PATH)%.cpp
	$(COMPILER) -o $@ $< $(QUAKE2_COMMON_COMPILE_FLAGS)

# Client module library.
$(CLIENT_NAME): BUILD_PATH := $(CLIENT_BUILD_PATH)
$(CLIENT_NAME): BUILD_OBJECTS := $(CLIENT_OBJECTS)
$(CLIENT_NAME): BUILD_FLAGS := $(CLIENT_LIBRARY_FLAGS)
$(CLIENT_NAME): VERSION_MAJOR := $(CLIENT_VERSION_MAJOR)
$(CLIENT_NAME): VERSION_FULL := $(VERSION_MAJOR).$(CLIENT_VERSION_MINOR).$(CLIENT_VERSION_BUILD)
$(CLIENT_NAME): create_$(CLIENT_NAME)_build_directory $(CLIENT_OBJECTS)
$(CLIENT_BUILD_PATH)%.o : $(CLIENT_SOURCE_PATH)%.cpp
	$(COMPILER) -o $@ $< $(CLIENT_COMPILE_FLAGS)

# OpenGL library target.
$(OPENGL_NAME): BUILD_PATH := $(OPENGL_BUILD_PATH)
$(OPENGL_NAME): BUILD_OBJECTS := $(OPENGL_OBJECTS)
$(OPENGL_NAME): BUILD_FLAGS := $(OPENGL_BUILD_FLAGS)
$(OPENGL_NAME): VERSION_MAJOR := $(OPENGL_VERSION_MAJOR)
$(OPENGL_NAME): VERSION_FULL := $(VERSION_MAJOR).$(OPENGL_VERSION_MINOR).$(OPENGL_VERSION_BUILD)
$(OPENGL_NAME): create_$(OPENGL_NAME)_build_directory $(OPENGL_OBJECTS)
$(OPENGL_BUILD_PATH)%.o : $(OPENGL_SOURCE_PATH)%.cpp
	$(COMPILER) -o $@ $< $(OPENGL_COMPILE_FLAGS)

# Generic library target.
$(LIBRARIES):
	$(COMPILER) \
		-o $(LIBRARY_OUTPUT_PATH)lib$@.so.$(VERSION_FULL) \
		-Wl,-soname,lib$@.so.$(VERSION_MAJOR) \
		$(BUILD_OBJECTS) \
		$(BUILD_FLAGS) \
		$(LIBRARY_BUILD_FLAGS)
	$(SYMBOLIC_LINK) -s -f \
		$(LIBRARY_OUTPUT_PATH)lib$@.so.$(VERSION_FULL) \
		$(LIBRARY_OUTPUT_PATH)lib$@.so.$(VERSION_MAJOR)
	$(SYMBOLIC_LINK) -s -f \
		$(LIBRARY_OUTPUT_PATH)lib$@.so.$(VERSION_FULL) \
		$(LIBRARY_OUTPUT_PATH)lib$@.so


# Clean up build directories.
CLEAN_PATHS := \
	$(addsuffix /$(BUILD_SUBDIRECTORY),$(LIBRARIES)) \
	$(QUAKE2_BUILD_PATH) \
	$(LIBRARY_OUTPUT_PATH) \
	$(EXECUTABLE_OUTPUT_PATH)
clean:
	rm -rf $(CLEAN_PATHS)

# Creating library directory.
create_library_directory:
	mkdir -p $(LIBRARY_OUTPUT_PATH)

# Create executable directory.
create_executable_directory:
	mkdir -p $(EXECUTABLE_OUTPUT_PATH)

# Creating build directory.
create_%_build_directory:
	mkdir -p $(BUILD_PATH)
